### ISSUE TITLE
[DB] Configure using function parameters

### ISSUE THREAD

**Issue by mcastellin** [mcastellin/py-bot-starter#12]
Db layer should accept MongoDB configuration parameters like hostname, port, username, password and database name from function parameters as well as environment variables.

**Definition of done**
- The `init_db()` function accepts db configuration as function call parameters and environment variables. 
- Integration tests are created to make sure we can setup the connection with all the possible ways

**Comment by diogokuiaski** [comment]
Hi, may I help with this issue?

**Comment by mcastellin** [comment]
Hey @diogokuiaski, absolutely yes!
I'll assign this to your name then :)

This is a very new project but I've setup a [Discord Server](https://discord.gg/VkcgpGx4) for collaboration, feel free to join in

**Comment by mcastellin** [comment]
PR merged for the implementation part. As part of the Definition of Done I included integration tests.
@diogokuiaski do you have any suggestion on how to approach integration testing with MondgoDB or shall we raise a separate issue for that?

**Comment by diogokuiaski** [comment]
Hi @mcastellin, I am not sure how to fit integration tests inside github. The first idea that came into my mind was to create a sample app, a mongodb docker with pre-existing data and try to fetch it.

I would love to write the tests, but need some guidance, a simple link with a tutorial would do the trick. But if it is not possible right now, better to create another issue.

**Comment by mcastellin** [comment]
I think you're right.. this type of tests should probably not run in a CI. I'm adding some sample bots to the repo next, maybe we could create a test BOT_TOKEN for those and run them in sequence or something.

Thanks for your contribution ⭐️ will close this ticket and raise a new one for later
