### ISSUE TITLE
Unit testing common package

### ISSUE THREAD

**Issue by mcastellin** [mcastellin/py-bot-starter#13]
Implement unit testing for common.py

Good first issue, implement unit tests for all methods in `src/botstarter/common.py`
1. go through existing methods and remove what isn't currently used
2. Add docstrings at package and function level
3.  implement good unit tests to consolidate every feature

**Comment by ceccatoandrea** [comment]
Hi, may I help with this issue?

**Comment by mcastellin** [comment]
Absolutely! Will assign the ticket on your name.

On a related note, just today I've configured the build pipeline to collect Code coverage reports. Code coverage information will be available here https://app.codecov.io/gh/mcastellin/py-bot-starter
